apiVersion: v1
kind: Namespace
metadata:
  name: openshift-jobset-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: job-set
  namespace: openshift-jobset-operator
spec:
  targetNamespaces:
    - openshift-jobset-operator
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: job-set
  namespace: openshift-jobset-operator
  labels:
    operators.coreos.com/job-set.openshift-jobset-operator: ''
spec:
  channel: stable-v1.0
  name: job-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
