apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kueue-allow-ingress-visibility
  namespace: openshift-kueue-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kueue # applies to the kueue pod only
  ingress:
  - from:
    - namespaceSelector: {}  # Allow from all namespaces (visibility server has RBAC controls)
    ports:
    - protocol: TCP
      port: visibility
  policyTypes:
  - Ingress
