apiVersion: v1
kind: Service
metadata:
  name: openshift-kueue-operator-metrics
  namespace: openshift-kueue-operator
  labels:
    app.openshift.io/component: operator
    app.openshift.io/name: kueue
spec:
  ports:
    - name: metrics
      port: 60000
      protocol: TCP
      targetPort: 8443
  selector:
    name: openshift-kueue-operator
  type: ClusterIP
